/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBookmark: typeof import('./src/components/AddBookmark.vue')['default']
    AddBookmarkDialog: typeof import('./src/components/AddBookmarkDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    AppSidebarNav: typeof import('./src/components/AppSidebarNav.vue')['default']
    AppTips: typeof import('./src/components/AppTips.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    BookmarkDetailsDialog: typeof import('./src/components/BookmarkDetailsDialog.vue')['default']
    BookmarkEditDialog: typeof import('./src/components/BookmarkEditDialog.vue')['default']
    BookmarkTable: typeof import('./src/components/BookmarkTable.vue')['default']
    BookmarkTableRow: typeof import('./src/components/BookmarkTableRow.vue')['default']
    ButtonAddBookmark: typeof import('./src/components/ButtonAddBookmark.vue')['default']
    ButtonDeleteBookmarks: typeof import('./src/components/ButtonDeleteBookmarks.vue')['default']
    ButtonDeleteBookmars: typeof import('./src/components/ButtonDeleteBookmars.vue')['default']
    JasperApiDemo: typeof import('./src/components/JasperApiDemo.vue')['default']
    KeyboardShortcutsDialog: typeof import('./src/components/KeyboardShortcutsDialog.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NotificationComponent: typeof import('./src/components/NotificationComponent.vue')['default']
    RecentBookmarks: typeof import('./src/components/RecentBookmarks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBookmarks: typeof import('./src/components/SearchBookmarks.vue')['default']
    UndoSnackbar: typeof import('./src/components/UndoSnackbar.vue')['default']
    UserNameAvatar: typeof import('./src/components/UserNameAvatar.vue')['default']
  }
}
