/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBookmark: typeof import('./src/components/AddBookmark.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSidebarNav: typeof import('./src/components/AppSidebarNav.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NotificationComponent: typeof import('./src/components/NotificationComponent.vue')['default']
    RecentBookmarks: typeof import('./src/components/RecentBookmarks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserNameAvatar: typeof import('./src/components/UserNameAvatar.vue')['default']
  }
}
