/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBookmark: typeof import('./src/components/AddBookmark.vue')['default']
    AddBookmarkDialog: typeof import('./src/components/AddBookmarkDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    AppSidebarNav: typeof import('./src/components/AppSidebarNav.vue')['default']
    AppTips: typeof import('./src/components/AppTips.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    BackgroundSelectionDialog: typeof import('./src/components/BackgroundSelectionDialog.vue')['default']
    BookmarkCard: typeof import('./src/components/BookmarkCard.vue')['default']
    BookmarkCardHeader: typeof import('./src/components/BookmarkCardHeader.vue')['default']
    BookmarkCardMenu: typeof import('./src/components/BookmarkCardMenu.vue')['default']
    BookmarkCardPagination: typeof import('./src/components/BookmarkCardPagination.vue')['default']
    BookmarkCardView: typeof import('./src/components/BookmarkCardView.vue')['default']
    BookmarkColorPicker: typeof import('./src/components/BookmarkColorPicker.vue')['default']
    BookmarkDeleteButton: typeof import('./src/components/BookmarkDeleteButton.vue')['default']
    BookmarkDetailsDialog: typeof import('./src/components/BookmarkDetailsDialog.vue')['default']
    BookmarkEditDialog: typeof import('./src/components/BookmarkEditDialog.vue')['default']
    BookmarkLoadingState: typeof import('./src/components/BookmarkLoadingState.vue')['default']
    BookmarkNoDataAlert: typeof import('./src/components/BookmarkNoDataAlert.vue')['default']
    BookmarkNoDataState: typeof import('./src/components/BookmarkNoDataState.vue')['default']
    BookmarkTable: typeof import('./src/components/BookmarkTable.vue')['default']
    BookmarkTableCollapseIndicator: typeof import('./src/components/BookmarkTableCollapseIndicators.vue')['default']
    BookmarkTableCollapseIndicators: typeof import('./src/components/BookmarkTableCollapseIndicators.vue')['default']
    BookmarkTableRow: typeof import('./src/components/BookmarkTableRow.vue')['default']
    BookmarkTableView: typeof import('./src/components/BookmarkTableView.vue')['default']
    BookmarkTagList: typeof import('./src/components/BookmarkTagList.vue')['default']
    ButtonAddBookmark: typeof import('./src/components/ButtonAddBookmark.vue')['default']
    GlobalDeleteHandler: typeof import('./src/components/GlobalDeleteHandler.vue')['default']
    JasperApiDemo: typeof import('./src/components/JasperApiDemo.vue')['default']
    KeyboardShortcutsDialog: typeof import('./src/components/KeyboardShortcutsDialog.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MdiDiscord: typeof import('./src/components/icons/MdiDiscord.vue')['default']
    MobileFAB: typeof import('./src/components/MobileFAB.vue')['default']
    NotificationComponent: typeof import('./src/components/NotificationComponent.vue')['default']
    PageNavigationIndicator: typeof import('./src/components/PageNavigationIndicator.vue')['default']
    RecentBookmarks: typeof import('./src/components/RecentBookmarks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBookmarks: typeof import('./src/components/SearchBookmarks.vue')['default']
    UndoSnackbar: typeof import('./src/components/UndoSnackbar.vue')['default']
    UnsplashCredits: typeof import('./src/components/UnsplashCredits.vue')['default']
    UserNameAvatar: typeof import('./src/components/UserNameAvatar.vue')['default']
  }
}
