/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/apidemo': RouteRecordInfo<'/apidemo', '/apidemo', Record<never, never>, Record<never, never>>,
    '/export': RouteRecordInfo<'/export', '/export', Record<never, never>, Record<never, never>>,
    '/generate-bookmarklet': RouteRecordInfo<'/generate-bookmarklet', '/generate-bookmarklet', Record<never, never>, Record<never, never>>,
    '/generate-pin': RouteRecordInfo<'/generate-pin', '/generate-pin', Record<never, never>, Record<never, never>>,
    '/import': RouteRecordInfo<'/import', '/import', Record<never, never>, Record<never, never>>,
    '/paths': RouteRecordInfo<'/paths', '/paths', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/search/[keyword]': RouteRecordInfo<'/search/[keyword]', '/search/:keyword', { keyword: ParamValue<true> }, { keyword: ParamValue<false> }>,
    '/tag/[tagtitle]': RouteRecordInfo<'/tag/[tagtitle]', '/tag/:tagtitle', { tagtitle: ParamValue<true> }, { tagtitle: ParamValue<false> }>,
    '/tags': RouteRecordInfo<'/tags', '/tags', Record<never, never>, Record<never, never>>,
  }
}
