// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efaaigzvqhgoozvdkhzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmYWFpZ3p2cWhnb296dmRraHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTUxNjksImV4cCI6MjA2NjYzMTE2OX0.TZqfgBFd-KqnrUSqVkfQTUz8lZHvdgGP-xrLl5HzxqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);